# 第9章/HomeSharing/docker-compose.yml

version: '3'

services:
  
  gateway:
    build: docker/gateway
    ports:
      - 80:80
    volumes:
      # 配置 Apache 服务器的根目录
      - "./app/static:/var/www/html"
  
  web:
    build: docker/web
    # 工作目录为 /opt/cms4py
    working_dir: /opt/cms4py
    volumes:
      # 将当前目前映射到到容器的 /opt/cms4py 目录
      - ".:/opt/cms4py"
    # 将服务器启动在 8000 端口上
    command: uvicorn --host 0.0.0.0 --port 8000 cms4py:application
  
  db:
    # 数据库镜像使用 mariadb
    image: mariadb
    restart: always
    environment:
      # 配置 root 用户密码为 rootpw
      MYSQL_ROOT_PASSWORD: rootpw
    ports:
      # 将端口映射到本机
      # 生产服务器上应该去掉该端口映射
      - 3306:3306
    volumes:
      # 将数据库存储地址映射到当前目录下的 mariadb_data 目录
      - "./mariadb_data:/var/lib/mysql"
  
  adminer:
    # adminer 是一个数据库管理系统
    image: adminer
    restart: always
    ports:
      # 将 adminer 的端口映射到本机，便于访问
      - 8080:8080