# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-19 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='命令名称')),
                ('command', models.CharField(max_length=200, verbose_name='命令')),
                ('result', models.CharField(max_length=2000, verbose_name='结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Team', verbose_name='发布项目')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='url')),
                ('bingfa', models.CharField(max_length=200, verbose_name='并发')),
                ('num', models.CharField(max_length=2000, verbose_name='次数')),
                ('result', models.CharField(max_length=2000, verbose_name='结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用户名称')),
                ('email', models.CharField(max_length=200, verbose_name='邮箱地址')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('role', models.CharField(choices=[('0', '开发'), ('1', '测试')], default='0', max_length=10, verbose_name='角色')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
