# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-19 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_command_test_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='test_user',
            field=models.ManyToManyField(related_name='测试人员', to='web.UserProfile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user_id',
            field=models.ManyToManyField(related_name='研发人员', to='web.UserProfile'),
        ),
    ]
