# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-21 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20181219_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_issue',
            name='type',
            field=models.CharField(choices=[('0', '文件'), ('1', 'git')], default='0', max_length=20, verbose_name='更新类型'),
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('0', '文件'), ('1', 'git')], default='0', max_length=20, verbose_name='更新类型'),
        ),
        migrations.AlterField(
            model_name='team',
            name='test_user',
            field=models.ManyToManyField(related_name='测试人员', to='web.UserProfile', verbose_name='测试人员'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user_id',
            field=models.ManyToManyField(related_name='研发人员', to='web.UserProfile', verbose_name='研发人员'),
        ),
    ]
