# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-25 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20181221_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Team', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='host_issue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile', verbose_name='发布人'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile', verbose_name='发布人'),
        ),
    ]
