# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-25 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181225_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='nginxupstarm',
        ),
        migrations.AddField(
            model_name='team',
            name='nginxupstream',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nginx upstream名称'),
        ),
    ]
